GET http://localhost:3127/items
###
GET http://localhost:3127/items/shirt
###
POST http://localhost:3127/items/new
Content-Type: application/json

{
  "item_id": "",
  "name": "blazer",
  "zipcode": 90210,
  "description": "plain white t-shirt",
  "price": 10,
  "image": "image"
}
###
DELETE http://localhost:3127/items/17